version: '3.8'

services:
  microservice:
    build:
      context: ./Services/microservice
    ports:
      - "8000:8000"
    environment:
      - MOCK_URL=http://mock_service:5001/mock-response
    depends_on:
      - mock_service

  mock_service:
    build:
      context: ./Services/mock
    ports:
      - "5001:5001"
    env_file:
      - ./.env